<a href="https://colab.research.google.com/github/githubbhavani/internship/blob/master/intern3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
 import numpy as np
 a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [0]:
 a = np.floor(10*np.random.random((3,4)))
  

In [6]:
a

array([[2., 8., 3., 7.],
       [9., 2., 3., 4.],
       [8., 3., 7., 8.]])

In [9]:
 a.resize((2,6))
  

IndentationError: ignored

In [10]:
a

array([[2., 8., 3., 7., 9., 2.],
       [3., 4., 8., 3., 7., 8.]])

In [12]:
 a.reshape(3,-1)
  

array([[2., 8., 3., 7.],
       [9., 2., 3., 4.],
       [8., 3., 7., 8.]])

In [0]:
 a = np.floor(10*np.random.random((2,2)))
   
    

In [16]:
a

array([[9., 9.],
       [6., 7.]])

In [0]:
 b = np.floor(10*np.random.random((2,2)))

In [19]:
b

array([[4., 2.],
       [7., 8.]])

In [0]:
from numpy import newaxis
      

In [23]:
 np.column_stack((a,b))     

array([[9., 9., 4., 2.],
       [6., 7., 7., 8.]])

In [0]:
 a = np.array([4.,2.])
  

In [26]:
a

array([4., 2.])

In [0]:
b = np.array([3.,8.])

In [29]:
np.column_stack((a,b))

array([[4., 3.],
       [2., 8.]])

In [30]:
a[:,newaxis]

array([[4.],
       [2.]])

In [31]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

array([[4., 3.],
       [2., 8.]])

In [34]:
 np.r_[1:4,0,4]

array([1, 2, 3, 0, 4])

In [0]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])

In [37]:
a

array([[1., 2.],
       [3., 4.]])

In [38]:
print(a)

[[1. 2.]
 [3. 4.]]


In [39]:
 a.transpose()

array([[1., 3.],
       [2., 4.]])

In [40]:
 np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [0]:
u = np.eye(4)

In [42]:
u

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [43]:
np.trace(u)

4.0

In [0]:
y = np.array([[5.], [7.]])


In [45]:
y

array([[5.],
       [7.]])

In [46]:
np.linalg.solve(a, y)

array([[-3.],
       [ 4.]])

In [0]:
from array import *
 

In [0]:
 my_array = array('i', [1,2,3,4,5,6,7,8,9,10])

In [61]:
 for i in my_array:
    print(i)

1
2
3
4
5
6
7
8
9
10


In [62]:
 my_array[7]

8

In [0]:
 my_array.append(11)

In [65]:
for i in my_array:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
11


In [0]:
 my_array.insert(2,0)

In [67]:
my_array

array('i', [1, 2, 0, 3, 4, 5, 6, 7, 8, 9, 10, 11, 11])

In [0]:
my_extnd_array = array('i', [12,13,14,15])


In [0]:
my_array.extend(my_extnd_array)

In [72]:
my_array

array('i', [1, 2, 0, 3, 4, 5, 6, 7, 8, 9, 10, 11, 11, 12, 13, 14, 15])

In [0]:
c=[11,12,13]
>>> my_array.fromlist(c)

In [75]:
my_array

array('i', [1, 2, 0, 3, 4, 5, 6, 7, 8, 9, 10, 11, 11, 12, 13, 14, 15, 11, 12, 13])

In [93]:
>>> my_array.remove(0)
>>> my_array

array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 11, 12, 14, 15, 11, 12])

In [95]:
>>> my_array.remove(12)
>>> my_array

array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 11, 14, 15, 11, 12])

In [92]:
 my_array.index(1)

0

In [98]:

>>> my_array

array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 11, 14, 15, 11, 12])

In [99]:
>>> my_array.reverse()
>>> my_array

array('i', [12, 11, 15, 14, 11, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

In [100]:
 my_array.buffer_info()

(140643987896112, 16)

In [101]:
my_array.count(11)

3

In [0]:
 m = array('b', [ord('g'),ord('e'),ord('e'),ord('k')])

In [118]:
m

array('b', [103, 101, 101, 107])

In [113]:
my_array

array('i', [12, 11, 15, 14, 11, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

In [119]:
c = my_array.tolist()
c

[12, 11, 15, 14, 11, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [0]:
m.fromstring("stuff")

In [121]:
m

array('b', [103, 101, 101, 107, 115, 116, 117, 102, 102])

In [0]:
pno=0
def p(n):
  if x>=2:
    for y in range(2,x):
      if not(x % y):
        return false
      else:
        return true
      
     
  

In [156]:
for i in range(int(raw_input("enter how many numbers:"))):
  if p(i):
    pno +=1
    print i
   
    
print "we found" +str(pno)+"prime"

SyntaxError: ignored

In [0]:
def isprime(n):
  if n==2 or n==3:return true
  if n<=2 or n%2 == 0:return false
  if n<9:return true
  if n%3==0:return false
  r=int(n**0.5)
  f=5
  while f<=r:
    print ('\t',f)
    if n%f ==0:return false
    if n%(f+2) ==0:return false
    f +=6
    return true

In [167]:
print isprime(1)

SyntaxError: ignored

In [170]:
a=random.ramdomint(100)

NameError: ignored

In [9]:
for i in range(0,100):
  if i % 2 == 0:
    print("even number:",i)
  else:
      print("odd number:",i)
      
print("{} is even"format(i) if i % 2==0 else "{} is odd"format(i))

SyntaxError: ignored

In [1]:
for i in range(0,100):
  if i % 2 != 0:
    continue
  else:
    print ("number is",i,"   even")
      

number is 0    even
number is 2    even
number is 4    even
number is 6    even
number is 8    even
number is 10    even
number is 12    even
number is 14    even
number is 16    even
number is 18    even
number is 20    even
number is 22    even
number is 24    even
number is 26    even
number is 28    even
number is 30    even
number is 32    even
number is 34    even
number is 36    even
number is 38    even
number is 40    even
number is 42    even
number is 44    even
number is 46    even
number is 48    even
number is 50    even
number is 52    even
number is 54    even
number is 56    even
number is 58    even
number is 60    even
number is 62    even
number is 64    even
number is 66    even
number is 68    even
number is 70    even
number is 72    even
number is 74    even
number is 76    even
number is 78    even
number is 80    even
number is 82    even
number is 84    even
number is 86    even
number is 88    even
number is 90    even
number is 92    even
number is 94    ev