<a href="https://colab.research.google.com/github/githubbhavani/internship/blob/master/intern3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
 import numpy as np
 a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [0]:
 a = np.floor(10*np.random.random((3,4)))
  

In [6]:
a

array([[2., 8., 3., 7.],
       [9., 2., 3., 4.],
       [8., 3., 7., 8.]])

In [9]:
 a.resize((2,6))
  

IndentationError: ignored

In [10]:
a

array([[2., 8., 3., 7., 9., 2.],
       [3., 4., 8., 3., 7., 8.]])

In [12]:
 a.reshape(3,-1)
  

array([[2., 8., 3., 7.],
       [9., 2., 3., 4.],
       [8., 3., 7., 8.]])

In [0]:
 a = np.floor(10*np.random.random((2,2)))
   
    

In [16]:
a

array([[9., 9.],
       [6., 7.]])

In [0]:
 b = np.floor(10*np.random.random((2,2)))

In [19]:
b

array([[4., 2.],
       [7., 8.]])

In [0]:
from numpy import newaxis
      

In [23]:
 np.column_stack((a,b))     

array([[9., 9., 4., 2.],
       [6., 7., 7., 8.]])

In [0]:
 a = np.array([4.,2.])
  

In [26]:
a

array([4., 2.])

In [0]:
b = np.array([3.,8.])

In [29]:
np.column_stack((a,b))

array([[4., 3.],
       [2., 8.]])

In [30]:
a[:,newaxis]

array([[4.],
       [2.]])

In [31]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

array([[4., 3.],
       [2., 8.]])

In [34]:
 np.r_[1:4,0,4]

array([1, 2, 3, 0, 4])

In [0]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])

In [37]:
a

array([[1., 2.],
       [3., 4.]])

In [38]:
print(a)

[[1. 2.]
 [3. 4.]]


In [39]:
 a.transpose()

array([[1., 3.],
       [2., 4.]])

In [40]:
 np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [0]:
u = np.eye(4)

In [42]:
u

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [43]:
np.trace(u)

4.0

In [0]:
y = np.array([[5.], [7.]])


In [45]:
y

array([[5.],
       [7.]])

In [46]:
np.linalg.solve(a, y)

array([[-3.],
       [ 4.]])

In [0]:
from array import *
 