<a href="https://colab.research.google.com/github/githubbhavani/internship/blob/master/intern2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
 import numpy as np
 a=np.array([1,2,3])
a

array([1, 2, 3])

In [12]:
import numpy as np
b=np.arange(3)
b

array([0, 1, 2])

In [15]:
a

array([1, 2, 3])

In [17]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [24]:
b=np.arange(10)**2
b

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [25]:
np.add(a,b)

array([  0,   2,  12,  36,  80, 150, 252, 392, 576, 810])

In [26]:
np.sqrt(b)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [32]:
B = np.arange(3)
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [33]:
a=([4,5])
a

[4, 5]

In [34]:
np.exp(a)

array([ 54.59815003, 148.4131591 ])

In [35]:
d=([1,3,5,7,9,11,13,15,17])
d

[1, 3, 5, 7, 9, 11, 13, 15, 17]

In [42]:
d[:10:4]

[1, 9, 17]

In [44]:
for i in d:
  print(i**(1/3.))


1.0
1.4422495703074083
1.7099759466766968
1.912931182772389
2.080083823051904
2.2239800905693152
2.3513346877207573
2.46621207433047
2.571281590658235


In [56]:
f=np.array([[(1,2,3,5),(1,1,1,5)],[(3,6,7,5),(3,3,3,5)],[(0,0,1,5),(2,2,2,5)],[(2,1,1,5),(4,4,4,5)]])
f

array([[[1, 2, 3, 5],
        [1, 1, 1, 5]],

       [[3, 6, 7, 5],
        [3, 3, 3, 5]],

       [[0, 0, 1, 5],
        [2, 2, 2, 5]],

       [[2, 1, 1, 5],
        [4, 4, 4, 5]]])

In [68]:
f[2,0:2:2]

array([[0, 0, 1, 5]])

In [76]:
c = np.array( [[[  0,  1,  2],             
                 [ 10, 12, 13]],[[  1,  1,  1],             
                 [ 4, 4, 4]],
                [[100,101,102],
                 [110,112,113]]])
c.shape


(3, 2, 3)

In [82]:
c

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[  1,   1,   1],
        [  4,   4,   4]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [83]:
c[1,...]

array([[1, 1, 1],
       [4, 4, 4]])

In [90]:
for ele in c.flat:
  print(ele)

0
1
2
10
12
13
1
1
1
4
4
4
100
101
102
110
112
113


In [130]:
a=np.floor(10*np.random.random((2,2)))
a

array([[1., 5.],
       [1., 1.]])

In [109]:
a.ravel()

array([6., 0., 7., 6., 5., 1., 6., 1., 1., 1., 3., 2., 4., 0., 0.])

In [128]:
a.reshape(1,12)

array([[4., 9., 1., 9., 3., 1., 4., 2., 0., 5., 8., 2.]])

In [129]:
 b = np.floor(10*np.random.random((2,2)))
b

array([[1., 3.],
       [0., 5.]])

In [132]:
from numpy import newaxis
 np.column_stack((a,b))     

IndentationError: ignored