<a href="https://colab.research.google.com/github/githubbhavani/internship/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
x=7
print(x)

7


In [4]:
 import numpy as np
>>> a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
a.ndim
A = np.array( [[1,1],
...             [0,1]] )
>>> B = np.array( [[2,0],
...             [3,4]] )

2

In [6]:
type(a)

numpy.ndarray

In [7]:
a.dtype.name

'int64'

2

In [16]:
>>> A = np.array( [[1,1,2],
...             [0,1,3],[2,3,1,0]] )
>>> B = np.array( [[2,0,1],
...             [3,4,5]] )
>>> A * B        

array([[list([1, 1, 2, 1, 1, 2]), list([]), list([2, 3, 1, 0])],
       [list([1, 1, 2, 1, 1, 2, 1, 1, 2]),
        list([0, 1, 3, 0, 1, 3, 0, 1, 3, 0, 1, 3]),
        list([2, 3, 1, 0, 2, 3, 1, 0, 2, 3, 1, 0, 2, 3, 1, 0, 2, 3, 1, 0])]],
      dtype=object)

In [22]:
a=np.array([[0,1,2,3]])
b=np.array([[0,1,3,4],[3,4,2,1]])
a*b

array([[ 0,  1,  6, 12],
       [ 0,  4,  4,  3]])

In [24]:
b.ndim

2

In [25]:
c=np.array([[(1,3,3),(5,7,6)],[(1,2,4),(5,6,7)]])
c

array([[[1, 3, 3],
        [5, 7, 6]],

       [[1, 2, 4],
        [5, 6, 7]]])

In [26]:
c.ndim


3